name: Bug report
description: Create a report to help us reproduce and fix a bug
labels: [bug]

body:
- type: markdown
  attributes:
    value: >
      #### Please check that the bug has not been previously notified before submitting, by searching through the [issues list](https://github.com/vnmabus/dcor/issues).
- type: textarea
  attributes:
    label: Bug description summary
    description: >
      Please describe the bug in a brief paragraph(s). Be clear and concise.
  validations:
    required: true
- type: textarea
  attributes:
    label: Code to reproduce the bug
    description: |
      Please add a minimal code example that can reproduce the error. This will be automatically converted to a Python block.
    placeholder: |
      import dcor
      import numpy as np
      
      a = np.array([1, 2, 3, 4], dtype=np.float64)
      b = np.array([5, 6, 7, 8], dtype=np.float64)

      dcor.distance_correlation(a, b, method="default")
    render: Python
- type: textarea
  attributes:
    label: Expected result
    description: >
      Paste or describe the result that you expected here.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual result
    description: >
      Paste or describe the result that you obtained here. If the code raises an error, you can past it in the next field.
  validations:
    required: true
- type: textarea
  attributes:
    label: Traceback (if an exception is raised)
    description: |
      If an exception is raised, copy and paste the traceback here.
    placeholder: |
        KeyError                                  Traceback (most recent call last)
        Cell In[10], line 7
              4 a = np.array([1, 2, 3, 4], dtype=np.float64)
              5 b = np.array([5, 6, 7, 8], dtype=np.float64)
        ----> 7 dcor.distance_correlation(a, b, method="default")
        
        File .../dcor/_dcor.py:1033, in distance_correlation(x, y, exponent, method, compile_mode)
            982 def distance_correlation(
            983     x: Array,
            984     y: Array,
           (...)
            988     compile_mode: CompileMode = CompileMode.AUTO,
            989 ) -> Array:
            990     """
            991     Usual (biased) estimator for the distance correlation.
            992 
           (...)
           1030 
           1031     """
           1032     return _sqrt(
        -> 1033         distance_correlation_sqr(
           1034             x,
           1035             y,
           1036             exponent=exponent,
           1037             method=method,
           1038             compile_mode=compile_mode,
           1039         ),
           1040     )
        
        File .../dcor/_dcor.py:909, in distance_correlation_sqr(x, y, exponent, method, compile_mode)
            859 def distance_correlation_sqr(
            860     x: Array,
            861     y: Array,
           (...)
            865     compile_mode: CompileMode = CompileMode.AUTO,
            866 ) -> Array:
            867     """
            868     Usual (biased) estimator for the squared distance correlation.
            869 
           (...)
            907 
            908     """
        --> 909     method = _to_algorithm(method)
            911     return method.value.stats_sqr(
            912         x,
            913         y,
            914         exponent=exponent,
            915         compile_mode=compile_mode,
            916     ).correlation_xy
        
        File .../dcor/_dcor.py:437, in _to_algorithm(algorithm)
            434 if isinstance(algorithm, DistanceCovarianceMethod):
            435     return algorithm
        --> 437 return DistanceCovarianceMethod[algorithm.upper()]
        
        File .../lib/python3.11/enum.py:790, in EnumType.__getitem__(cls, name)
            786 def __getitem__(cls, name):
            787     """
            788     Return the member matching `name`.
            789     """
        --> 790     return cls._member_map_[name]
        
        KeyError: 'DEFAULT'
    render: Python
- type: textarea
  attributes:
    label: Software versions
    description: >
      Include the version of the library used (obtained with `dcor.__version__`). If relevant, you can include here the OS version and versions of related software.
    placeholder: |
      dcor version: 0.6
      OS: Windows 10
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context
    description: >
      Add any other context about the problem here.
