name: Feature request
description: Suggest an idea for this project
labels: [enhancement]

body:
- type: markdown
  attributes:
    value: >
      #### Please check that this idea has not been proposed previously, by searching through the [issues list](https://github.com/vnmabus/dcor/issues).
- type: textarea
  attributes:
    label: Motivation
    description: >
      A clear and concise description of what the problem is. Ex. I am always frustrated when [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Desired functionality
    description: >
      A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives
    description: >
      A clear and concise description of any alternative solutions or features you have considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: >
      Add any other context about the problem here.
